import type { ExpoConfig } from 'expo/config';

/**
 * Dynamic Expo configuration (D1).
 *
 * This file is the ONLY source of truth for Info.plist and entitlements.
 * Native files are never edited by hand: ios/ is regenerated by CI on every
 * build and is not committed.
 *
 * Two distinct application identifiers, therefore two distinct installations
 * and two distinct containers:
 *
 *   APP_VARIANT=dev         com.billjackpot.suiviapp.dev   throwaway database
 *   APP_VARIANT=production  com.billjackpot.suiviapp       real data
 *
 * The default is deliberately "dev". Forgetting the variable must never
 * produce a binary that overwrites the daily installation: a wrong dev build
 * costs a CI cycle, a wrong production build costs the container.
 *
 * Changing BUNDLE_ID_PRODUCTION wipes the daily installation's container
 * without warning (specs 2.2). It is a one-way decision.
 */

const BUNDLE_ID_PRODUCTION = 'com.billjackpot.suiviapp';
const BUNDLE_ID_DEV = 'com.billjackpot.suiviapp.dev';

type Variant = 'dev' | 'production';

function readVariant(): Variant {
  const raw = process.env.APP_VARIANT;
  if (raw === 'production') return 'production';
  if (raw === 'dev' || raw === undefined || raw === '') return 'dev';
  throw new Error(
    `APP_VARIANT must be "dev" or "production", received "${raw}". ` +
      'Refusing to guess: the wrong value targets the wrong container.',
  );
}

const variant = readVariant();
const isProduction = variant === 'production';

// Incremented by CI so SideStore can tell two builds apart. Local builds stay at 1.
const buildNumber = process.env.BUILD_NUMBER ?? '1';

const config: ExpoConfig = {
  name: isProduction ? 'Suivi' : 'Suivi dev',
  slug: 'suiviapp',
  version: '0.1.0',
  orientation: 'portrait',
  icon: './assets/icon.png',
  scheme: isProduction ? 'suiviapp' : 'suiviapp-dev',

  // Light / dark / system theme tokens follow the OS setting (D10).
  userInterfaceStyle: 'automatic',

  ios: {
    bundleIdentifier: isProduction ? BUNDLE_ID_PRODUCTION : BUNDLE_ID_DEV,
    buildNumber,
    supportsTablet: false,
    infoPlist: {
      // D2: the data folder must be reachable from the Files app, so that the
      // pre-migration backup can be retrieved by hand after a G3 refusal.
      // These are plain Info.plist keys, not entitlements, so unlike HealthKit
      // (test B) they should survive SideStore re-signing.
      UIFileSharingEnabled: true,
      LSSupportsOpeningDocumentsInPlace: true,
    },
  },

  plugins: ['expo-router'],

  extra: {
    variant,
  },
};

export default config;
