import type { ExpoConfig } from 'expo/config';

/**
 * Dynamic Expo configuration (D1).
 *
 * This file is the ONLY source of truth for Info.plist and entitlements.
 * Native files are never edited by hand: ios/ is regenerated by CI on every
 * build and is not committed.
 *
 * Two distinct application identifiers, therefore two distinct installations
 * and two distinct containers:
 *
 *   APP_VARIANT=dev         com.billjackpot.suiviapp.dev   throwaway database
 *   APP_VARIANT=production  com.billjackpot.suiviapp       real data
 *
 * The default is deliberately "dev". Forgetting the variable must never
 * produce a binary that overwrites the daily installation: a wrong dev build
 * costs a CI cycle, a wrong production build costs the container.
 *
 * Changing BUNDLE_ID_PRODUCTION wipes the daily installation's container
 * without warning (specs 2.2). It is a one-way decision.
 */

const BUNDLE_ID_PRODUCTION = 'com.billjackpot.suiviapp';
const BUNDLE_ID_DEV = 'com.billjackpot.suiviapp.dev';

type Variant = 'dev' | 'production';

function readVariant(): Variant {
  const raw = process.env.APP_VARIANT;
  if (raw === 'production') return 'production';
  if (raw === 'dev' || raw === undefined || raw === '') return 'dev';
  throw new Error(
    `APP_VARIANT must be "dev" or "production", received "${raw}". ` +
      'Refusing to guess: the wrong value targets the wrong container.',
  );
}

const variant = readVariant();
const isProduction = variant === 'production';

// Incremented by CI so SideStore can tell two builds apart. Local builds stay at 1.
const buildNumber = process.env.BUILD_NUMBER ?? '1';

const config: ExpoConfig = {
  name: isProduction ? 'Suivi' : 'Suivi dev',
  slug: 'suiviapp',
  version: '0.1.0',
  orientation: 'portrait',
  /**
   * ONE ICON PER VARIANT, because there was one for both.
   *
   * Both installations sit on the same home screen — specs 2.2 makes them two
   * identifiers, two containers, one holding real data and one a throwaway —
   * and until now they looked identical. Launching the wrong one is cheap;
   * exporting from the wrong one, or trusting a figure read on the wrong one,
   * is not.
   *
   * Both are drawn by scripts/generate-icons.mjs rather than stored as opaque
   * binaries: see that file for why the development one is amber with DEV
   * across it rather than a tinted version of the same picture.
   */
  icon: isProduction ? './assets/icon.png' : './assets/icon-dev.png',
  scheme: isProduction ? 'suiviapp' : 'suiviapp-dev',

  // Light / dark / system theme tokens follow the OS setting (D10).
  userInterfaceStyle: 'automatic',

  ios: {
    bundleIdentifier: isProduction ? BUNDLE_ID_PRODUCTION : BUNDLE_ID_DEV,
    buildNumber,
    supportsTablet: false,
    infoPlist: {
      // D2: the data folder must be reachable from the Files app, so that the
      // pre-migration backup can be retrieved by hand after a G3 refusal.
      // These are plain Info.plist keys, not entitlements, so unlike HealthKit
      // (test B) they should survive SideStore re-signing.
      UIFileSharingEnabled: true,
      LSSupportsOpeningDocumentsInPlace: true,
    },
  },

  plugins: [
    'expo-router',
    /**
     * The barcode scanner (specs 8.5, slice 4).
     *
     * ## THE REASON RECORDED IN SLICE 4 WAS WRONG, AND THE DECLARATION IS
     * ## RIGHT ANYWAY
     *
     * Slice 4 wrote that this had to be declared because autolinking cannot
     * write NSCameraUsageDescription, so the alternative was a crash. Measured
     * in slice 9, by running prebuild with this entry removed: the key IS
     * written without it, carrying the package's own default —
     * "Allow $(PRODUCT_NAME) to access your camera". There is no crash to
     * avoid, because a package's config plugin is auto-applied on SDK 57.
     *
     * What the declaration actually buys is the TEXT, and that is reason
     * enough. The string is shown in the system prompt, so it is French like
     * every other displayed string (conventions section 4), and it says what
     * the camera is FOR: a prompt that only says "this app would like to use
     * the camera" is the prompt people refuse.
     *
     * Kept rather than corrected into nothing — but the belief it rested on is
     * corrected here, because the same belief is what nearly shipped an APNs
     * entitlement three slices later.
     *
     * No microphone permission: the barcode scanner does not record audio, and
     * asking for something unused is how an application gets refused.
     */
    [
      'expo-camera',
      {
        cameraPermission:
          'Suivi utilise l’appareil photo pour scanner le code-barres d’un produit et retrouver ses valeurs nutritionnelles.',
        recordAudioAndroid: false,
      },
    ],
    /**
     * REMOVES the APNs entitlement expo-notifications adds on its own (slice 9).
     *
     * Not a plugin for a feature — a plugin that UNDOES one, and it is here
     * because a belief this project held turned out to be false.
     *
     * Slice 2 recorded that expo-sharing's plugin does not run because it is
     * not listed here. It does run: on SDK 57 a package's config plugin is
     * AUTO-APPLIED, and the reason expo-sharing never added a share extension
     * target is that its plugin is inert unless props.ios.enabled is passed.
     * The effect was true, the cause was not.
     *
     * So leaving expo-notifications unlisted does not keep its plugin away.
     * `expo prebuild` with nothing declared wrote aps-environment into
     * Suivi.entitlements — the push capability, which a free Apple account does
     * not have and SideStore cannot sign. Exactly the failure test B had with
     * HealthKit, and D14 refused to bet on anything the signature could shave
     * off.
     *
     * Local notifications need none of it: registerForRemoteNotifications lives
     * only in PushTokenModule, reached only from getDevicePushTokenAsync, which
     * nothing in this project calls.
     *
     * LAST IN THE LIST, so it runs after the plugin it undoes. Verified by the
     * preflight rather than assumed — see the file.
     */
    './plugins/with-no-aps-environment',
  ],

  extra: {
    variant,
  },
};

export default config;
