import { monotonicFactory } from 'ulid';

/**
 * Entity identifiers (D4).
 *
 * Textual, sortable by creation date, generated by the application and never
 * by the database. The reason is optionality on an irreversible decision:
 * identifiers travel inside the export (D7), and integers handed out by the
 * database would collide silently the day two databases are ever merged.
 *
 * Branded per table, so an identifier can never be passed where another kind
 * of identifier is expected. Conventions, section 4, asks for marked types on
 * LocalDate and entity identifiers; this is the second half of that.
 */

declare const entityIdBrand: unique symbol;

export type EntityId<TTable extends string> = string & {
  readonly [entityIdBrand]: TTable;
};

/**
 * The PRNG is supplied on purpose, and not left to the library.
 *
 * ulid picks its own generator by looking for crypto.getRandomValues on the
 * global object, and THROWS when it finds nothing. Neither React Native 0.86
 * nor the Expo runtime defines it: there is no Web Crypto in Hermes, and the
 * winter polyfills cover AbortSignal, FormData, TextDecoder and URL but not
 * crypto. A bare ulid() call would therefore throw on the device at the first
 * identifier generated, while working perfectly in Node during tests.
 *
 * Adding expo-crypto would fix it at the price of a native dependency absent
 * from section 5 — an event, by the rules of this project, for no benefit:
 *
 *  - monotonicFactory increments the random field for identifiers created
 *    within the same millisecond rather than drawing a new one, so a collision
 *    is structurally impossible whatever the generator's quality;
 *  - across milliseconds the timestamp already separates them;
 *  - a single user on a single device has exactly one generator, and these
 *    identifiers are not secrets, tokens, or capabilities.
 *
 * Math.random is therefore sufficient here, and costs no native surface.
 */
const nextUlid = monotonicFactory(() => Math.random());

/** Mints an identifier for a table. `newId<DayMealId>()`. */
export function newId<T extends EntityId<string>>(): T {
  return nextUlid() as T;
}
